''' 
Arquivo de configuração para o nginx
Protege o sistema e tudo que passa por ele 
'''
server { # Inicia o servidor virtual nginx
  listen 80; # Escuta a porta 80 no container, no computador é a porta http://localhost:8080
  server_name _; # Nome genérico 

  # Autenticação de entrada
  auth_basic "Observatory Control"; # Ativa o Basic Auth, o navegador irá mostrar uma janela que pede o usuário e a senha 
  auth_basic_user_file /etc/nginx/.htpasswd; # Aponta para o arquivo que contém usuário e senha no container

  client_max_body_size 20m; # Limita os uploads em até 20 MB, evita asssim payloads muito grandes que podem dar problema no sistema

  # Host Manager
  location / { # Define que qualquer outro caminho que não seja o indico no sistema não funcione
    proxy_pass http://host_manager:9000/; # Encaminha os requisitos para o Host Manager que se encontra na porta 9000, sai da porta 8080 e vai para a 9000

    proxy_http_version 1.1; # Usa essa versão do HTTP no proxy
    proxy_set_header Upgrade $http_upgrade; # Repassa o cabeçalho 
    proxy_set_header Connection "upgrade"; # Repassa o Connection

    proxy_set_header Host $host; # Passa o host original recebido pelo nginx
    proxy_set_header X-Real-IP $remote_addr; # Informa o IP do cliente para o sistema
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Cadeia de proxy no cabeçalho
    proxy_set_header X-Forwarded-Proto $scheme; # Verifica o protocolo original 

    proxy_redirect off; # Desativa a reescrita automática de redirects
    proxy_read_timeout 3600; # Até 3600 segundos de leitura
    proxy_send_timeout 3600; # Até 3600 segundos de envio -> esses tempos altos são usados pois o Host Manager fica aberto por longos períodos de tempo
  }


 # Grafana
  location /grafana/ { # Define tudo que vem do grafana 
    proxy_pass http://grafana:3000; # Encaminha para a porta 3000, que é referente ao grafana -> vai da porta 8080 para a 3000

    proxy_http_version 1.1; # Usa essa versão do HTTP no proxy
    proxy_set_header Upgrade $http_upgrade; # Repassa o cabeçalho 
    proxy_set_header Connection "upgrade"; # Repassa o Connection

    proxy_set_header Host $host; # Mantem o host original 
    proxy_set_header X-Real-IP $remote_addr; # Informa o IP do cliente 
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Repassa a cadeia de API
    proxy_set_header X-Forwarded-Proto $scheme; # Verifica o protocolo original
    proxy_set_header X-Forwarded-Prefix /grafana; # Serve sob o prefixo /grafana

    proxy_read_timeout 3600; # Até 3600 segundos de leitura
    proxy_send_timeout 3600; # Até 3600 segundos de envio
  }

  # API 
  location /api/ { # Define que tudo que começa com API segue esse padrão 
    proxy_pass http://sequencer:8000/; # Encaminha tudo que vem para o sequenciador 

    proxy_set_header Host $host; # Mantem o host original 
    proxy_set_header X-Real-IP $remote_addr; # Informa o IP do cliente
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # Passa a cadeia de IP
    proxy_set_header X-Forwarded-Proto $scheme; # Verifica o protocolo original
    proxy_set_header X-Forwarded-Prefix /api; # Informa o prefixo /api
  }

  location = /openapi.json { # Cria um match para esse sistema 
    proxy_pass http://sequencer:8000/openapi.json; # Encaminhao para o OpenAI JSON do sequenciador
    proxy_set_header Host $host; # Mantem o host original
    proxy_set_header X-Forwarded-Proto $scheme; # Passa o protocolo original 
  }
  
# InfluxDB
  location /influx/ { # Define tudo que vem do InflxDB
    proxy_pass http://influxdb:8086/;   # Encaminha para a porta do Influx que é a 8086
  }
}
