# Mosquitto MQTT broker configuration.
# É como se fosse o correio 
listener 1883 # Cria um listener na porta 1883, é onde o telegraf, o sequencer e o mqtt_logger se conectam 
protocol mqtt # Define que o listener vai ser em MQTT

listener 9001 # Cria mais um listener na porta 9001
protocol websockets # Define que esse listener usa MQTT sobre WebSocket

allow_anonymous true 
persistence true # Ativa a permanência
persistence_location /mosquitto/data/ # Salva os dados no containe
log_dest stdout # Manda os logs de volta para a saída normal do container
